# Shared MySQL database settings
app_db_name: ghost
app_db_user: ghostuser

app_db_password: password # Careful this should be using VAULT!!!!

k8s_namespace: ghost

tmp_folder_path: tmp # Should be in a relative path to the project folder
k8s_files_path: tmp # Should be in a relative path to the project folder

mail_transport: SMTP

mail_options_service: Mailgun
mail_options_auth_user: postmaster@sandbox49d1543ba9ca4600a82b8e8827de916f.mailgun.org
mail_options_auth_pass: 8ea1b9f57c51e302d948726dd5bbba2a-c2efc90c-d3f66810

first_blog_admin:
    name: ascn
    password: ascn123
    email: ascn@example.com


test_name: TEST
test_name1: TAST

n_replicas: 3