apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-name
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName:  disk-name
    fsType: ext4