---
# Playbook to test the full deployment of Ghost (from creation to destruction)

#- import_playbook: deploy-ghost.yml

- name: Change DB
  hosts: localhost
  gather_facts: true
  roles:
    - { role: create_blog_admin }
    - { role: changeDB }

- import_playbook: undeploy-ghost.yml

- import_playbook: deploy-ghost.yml

- name: See if memory is persistent 
  hosts: localhost
  gather_facts: true
  roles:
    #- { role: create_blog_admin }
    - { role: checkPersistentMemory }

- import_playbook: undeploy-ghost.yml delete_data='true'

- name: See if memory is back to normal 
  hosts: localhost
  gather_facts: true
  roles:
    #- { role: create_blog_admin }
    - { role: checkDeletePVC }

#- import_playbook: deploy-ghost.yml

#- name: Tests
#  hosts: localhost
#  gather_facts: yes
#  roles:
#    - { role: test_ghost }

#- import_playbook: undeploy-ghost.yml delete_data='true'
