---
- name: Create Ghost service file
  template:
    src: ghost-service
    dest: '{{ tmp_folder_path }}/ghost-service.yml'

- name: Deploy Ghost Service
  k8s:
    state: present
    src: '{{ tmp_folder_path }}/ghost-service.yml'
    wait: yes

- name: Get Ghost service
  k8s_info:
    kind: Service
    api_version: v1
    name: ghost-service
    namespace: ghost
  register: ghost_service
  until: ghost_service.resources[0].status.loadBalancer.ingress[0] is defined
  delay: 20
  retries: 5

- name: Register Ghost External Ip
  set_fact:
    ghost_ip: '{{ ghost_service.resources[0].status.loadBalancer.ingress[0].ip }}'

- name: Print Ghost service Ip
  debug:
    var: ghost_ip

- name: Change Ghost Service External Ip in gcp config
  lineinfile:
    dest: 'inventory/gcp.yml'
    regexp: 'ghost_ip: .*'
    line: '    ghost_ip: {{ ghost_ip }}'
    state: present
    backrefs: yes

- name: Create Ghost deployment file
  template:
    src: ghost-deployment
    dest: '{{ tmp_folder_path }}/ghost-deployment.yml'

- name: Deploy Ghost
  k8s:
    state: present
    src: '{{ tmp_folder_path }}/ghost-deployment.yml'
    wait: yes
