---
- name: Create MySQL deployment file
  template:
    src: mysql-deployment
    dest: "{{ tmp_folder_path }}/mysql-deployment.yml"

- name: Create MySQL pvc file
  template:
    src: mysql-pvc
    dest: "{{ tmp_folder_path }}/mysql-pvc.yml"

- name: Create MySQL service file
  template:
    src: mysql-service
    dest: "{{ tmp_folder_path }}/mysql-service.yml"

- name: Add MySQL Persistent Volume Claim
  k8s:
    state: present
    src: "{{ tmp_folder_path }}/mysql-pvc.yml"
    wait: yes

- name: Deploy MySQL
  k8s:
    state: present
    src: "{{ tmp_folder_path }}/mysql-deployment.yml"
    wait: yes

- name: Deploy MySQL Service
  k8s:
    state: present
    src: "{{ tmp_folder_path }}/mysql-service.yml"
    wait: yes
