---
- name: Refresh inventory
  meta: refresh_inventory


# Para ter ip da db
# kubectl get all --selector=tier=database

#- name: Get pod name
#  shell: kubectl get all --selector=tier=database
#  register: pod_db

- name: Get pod name
  kubernetes.core.k8s_info:
    kind: Pod
    label_selectors:
      - tier in (database)
  register: pod_db


- name: Change pod name variable
  set_fact:
    pod_db: '{{ pod_db.resources[0].metadata.name }}'

- debug: msg="{{ pod_db}}"

#- name: Get query
#  shell: kubectl exec -it {{pod_db}} -- mysql -Ns -e "use ghost; SELECT * FROM users;"
#  register: output

# Caso dê erro, usar isto :)
# https://stackoverflow.com/questions/66454603/get-list-of-k8s-pod-using-ansible
- name: Get if Admin is back to normal
  community.kubernetes.k8s_exec:
    namespace: "{{k8s_namespace}}"
    pod: "{{pod_db}}"
    command: mysql -Ns -e "use {{ app_db_name }}; SELECT * FROM users;" 
    #command: echo "Hello"
  register: answer

- debug: msg="{{ answer.stdout_lines }}"

#- debug:
#    msg: "matched pattern 1"
#  when: answer.stdout_lines[0] is not regex("1\tascn\tghost-user\t/\w+\tascn@example.com/\w+")
  
- name: Check if user is in DB
  fail:
    msg: Username not found
  when: answer.stdout_lines[0] is not regex("1\tascn\tghost-user")
 
- name: Check that you can connect (GET) to Ghost and it returns a status 200
  ansible.builtin.uri:
    url: 'http://{{ ghost_ip }}:{{ghost_port}}/'
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 3
  delay: 5

