---

- name: Install pre-requisites
  pip:
    name:
      - kubernetes==12.0.0
      - bcrypt


- name: Create namespace
  k8s:
    name: "{{ k8s_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    wait: yes

- name: Create temporary folder
  file:
    path: tmp
    state: directory

- name: Set Namespace Preference
  shell: kubectl config set-context --current --namespace={{ k8s_namespace }}

#- name: PV?
  #shell: kubectl apply -f persistent-volume.yml
