---
- name: Install pre-requisites
  pip:
    name:
      - kubernetes
      - bcrypt

- name: Create namespace
  k8s:
    name: "{{ k8s_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    wait: yes

- name: Create temporary folder
  file:
    path: tmp
    state: directory

- name: Set Namespace Preference
  shell: kubectl config set-context --current --namespace={{ k8s_namespace }}

- name: Create a Cloud Monitoring dashboard
  shell: "gcloud monitoring dashboards create --config-from-file=dashboards/monitoring.json"
